### ISSUE TITLE
plain-text code block incompatibility with Jekyll

### ISSUE THREAD

**Issue by adehghanzadeh** [emoriarty/notion_to_md#26]
Hi
Several days ago I tried [notion-to-md (npm)](https://github.com/souvikinator/notion-to-md/) and asked for [fixing a problem](https://github.com/souvikinator/notion-to-md/issues/47)  which is more relevant to Jekyll

> Hi
> 
> `plain text` code parts converted to
> 
> ```
> ```plain text
> ```
> 
> instead of
> 
> ```
> ```text
> ```
> 
> not supported in jekyll
> 
> ```
> it is text
> ```
> 
> ```
> it is plain text
> ```
> 
> ![image](https://user-images.githubusercontent.com/86428901/181935556-25e2ac8f-f46c-448f-a96e-7fd49733a7b8.png)
> 
> For instence, I created this blog post: https://adehghanzadeh.github.io/Jekyll_minimal-mistake/try-to-deploy-this-blog-to-cloudflare-pages/

I switched to [jekyll-notion](https://github.com/emoriarty/jekyll-notion) and this problem exists

**Comment by emoriarty** [comment]
Hey 👋 

Thanks for reporting the issue.

I've had a look at [markdown support for "Fenced Code Blocks"](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) and it says nothing about `text` or `plain text`.

I guess it depends on the markdown processor to treat one, the other, or both formats for syntax highlighting.

I think this issue is more related to how Jekyll treats spaces in code block format.
I've tested what you mean on my blog and yes, the output is a you mention

**Comment by emoriarty** [comment]
Hey 👋 

Thanks for reporting the issue.

I've had a look at [markdown support for "Fenced Code Blocks"](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) and there's no mention of `text` or `plain text` format.

I guess it depends on the markdown processor. Some will deal with one format or the other, or even both.

Anyway, I don't think this issue is related to the format but to how Jekyll treats spaces in code block format.

I've tested what you mean on my blog and yes, the output is as you mention.
<img width="658" alt="Screen Shot 2022-08-03 at 16 44 58" src="https://user-images.githubusercontent.com/510375/182637615-720485cf-1127-4867-85e0-72a3a9dd78be.png">

After changing the format to `text`, the new output is OK:
<img width="655" alt="Screen Shot 2022-08-03 at 16 46 50" src="https://user-images.githubusercontent.com/510375/182638119-b6400dde-03ab-4389-a396-05b552108f9a.png">

Even using `plaintext` or `whatever` is still working OK.

To confirm my theory, I've used a random code format name with spaces (`bla bla`) and the result is a bad formatted code block as the first sample.

I don't think this is an issue related to `notion_to_md` but a Jekyll issue treating spaces in code formats.

Can you open an issue in jekyll-notion?

**Comment by emoriarty** [comment]
Well, after all as @souvikinator says, it does not matter `plain text` or `text`.
In the next release, the fix will be available.

Thanks again @adehghanzadeh.

**Comment by adehghanzadeh** [comment]
Thanks for your response

Glad to help this project ❤️
